
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=api_cursos
        ports:
            - 5432:5432